apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-api
      version: v2
  template:
    metadata:
      labels:
        app: chat-api
        version: v2
    spec:
      containers:
      - name: chat-api
        image: hussain2844/chat:v2
