apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-api
  template:
    metadata:
      labels:
        app: risk-api
    spec:
      containers:
      - name: risk-api
        image: hussain2844/risk
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
